### ISSUE TITLE
No application open ( when control moves to a different file

### ISSUE THREAD

**Issue by MoniRaj1** [Accruent/robotframework-zoomba#113]
Hi,
We have a test script to  Open and launch the application( desktop app )
The next file is to perform subsequent checks on the opened application. 
The first file executes successfully ( means application is opened ), but when the control is moved to the second script "no open application " is thrown.

How can I resolve this ?

My setup includes ( DesktopLibrary - Zoomba )

**Comment by Wolfe1** [comment]
@MoniRaj1 Mind posting a code example and saying exactly which line gives you that error?

**Comment by Wolfe1** [comment]
Also reading your message again, it seems you have two separate robot files that are running tests on the same open application? If your second script is expecting an app to be open already you will need to 'attach' to the open application by using [Switch Application by Name](https://accruent.github.io/robotframework-zoomba/DesktopLibraryDocumentation.html#Switch%20Application%20By%20Name) or [Switch Application](https://accruent.github.io/robotframework-zoomba/DesktopLibraryDocumentation.html#Switch%20Application) (provided you set an alias for your application when you first open it)

The robot files will not share execution information between each other (such as the application under test). The usual best practice with test suite robot files is for them to be able to run without other tests influencing them.

**Comment by MoniRaj1** [comment]
Hi , 
Thank you for your response
Here's the code snippet

test.robot

*** Settings ***
 Suite Setup       Start App
 Suite Teardown    Close All Applications
 Test Setup        App Running
 Test Teardown     Quit Application
 Force Tags        Windows
 Library           ../../src/Zoomba/DesktopLibrary.py
 Library           ../method.py


*** Variables ***
 ${REMOTE_URL}  ${URLPath}
 ${APP}  ${ApplicationPath}

*** Keywords ***
 Start App
    Open Application    ${REMOTE_URL}    platformName=Windows    deviceName=Windows    
    app=${APP}

*** Test Cases ***
 Test Case 1
     Click on a element in the application
     #Click on a element in the application is defined in another file method.py ( which is imported 
      here )



----------------------------------------method.py---------------------------------------------------------------
from src.Zoomba.DesktopLibrary import DesktopLibrary
  def Click_on_a_element_in_the_application():
        DesktopLibrary.click_element(self,locator='ElementPath')

**Comment by MoniRaj1** [comment]
@Wolfe1  , in response to your second comment . 
I'm not using two robot files , I m using one robot and another python file.
I m trying to move control from robot file to python file and vice versa .
Kindly help me out
Thanks

**Comment by Wolfe1** [comment]
So the issue here is that you have two instances of DesktopLibrary, one in the robot file and one in the python file. You open the application with your robot file instance and then attempt to click on an element in your python instance (which has not opened an application and has no knowledge of the other instance).

The easiest solution I see is to remove the DesktopLibrary import from the robot file. Then when you call 'Open Application' it will run from your python file and in turn the same DesktopLibrary instance. 

Working example using the Windows Calculator:

```
*** Settings ***
Library          test.py
Suite Setup     Start App
Test Setup      Launch Application
Test Teardown   Quit Application
Suite Teardown    Close All Applications
Force Tags        Windows

*** Variables ***
${REMOTE_URL}           http://localhost:4723/wd/hub
${APP}                  Microsoft.WindowsCalculator_8wekyb3d8bbwe!App

*** Keywords ***
Start App
    Open Application        ${REMOTE_URL}     platformName=Windows    deviceName=Windows   app=${APP}
    Maximize Window
    Quit Application

*** Test Cases ***
Wait For And Click Element By Id Keyword Test
    click on a element in the application       accessibility_id=num2Button
    Wait Until Page Contains      2
```

------------------------------------------------------------------------------------

test.py:

```
from Zoomba.DesktopLibrary import DesktopLibrary
from robot.api.deco import keyword


class test(DesktopLibrary):
    def get_keyword_names(self):
        """
        This function restricts the keywords used in the library. This is to prevent incompatible keywords from imported
        libraries from being referenced and used.
        """
        keyword_list = DesktopLibrary.get_keyword_names(self)
        keyword_list.append('Click_on_a_element_in_the_application')
        return keyword_list

    @keyword('Click on a element in the application')
    def Click_on_a_element_in_the_application(self, locator):
        self.click_element(locator=locator)

```

Your keywords will have to be added to get_keyword_names to be usable.

Note that it is very important that your python file name and your python class name match exactly, otherwise robot will not instantiate it.

**Comment by MoniRaj1** [comment]
Hi @Wolfe1 

Thank you very much for your support .
Your response is really helpful.

**Comment by Wolfe1** [comment]
@MoniRaj1 No problem. Going to go ahead and close but feel free to raise a new issue if you have any more.
