### ISSUE TITLE
“Xpath Should Match X Times” keyword does not work when using DesktopLibrary

### ISSUE THREAD

**Issue by david-au** [Accruent/robotframework-zoomba#118]
Hi,

Since DesktopLibrary overrides the implementation of _element_find from AppiumLibrary and returns only a single WebElement, it does not work with the “Xpath Should Match X Times” keyword from AppiumLibrary which expects _element_find to return a collection so that it can apply the len() function on it.

**Comment by Wolfe1** [comment]
Hey @david-au , 

I will take a look at this, in the meantime if you downgrade to version 2.3.1 this functionality should work as intended for you until we have a fix.

pip install robotframework-zoomba==2.3.1

**Comment by Wolfe1** [comment]
@david-au well scratch that, still working on it but feel free to try out the pull request above

**Comment by Wolfe1** [comment]
@david-au try updating to latest and see if that works for you now. Let me know if you have issues.

pip install robotframework-zoomba --upgrade

**Comment by david-au** [comment]
@Wolfe1 The fix works. Ty
