### ISSUE TITLE
Can zoomba library be used to automate cross platform desktop applications ( specifically for windows and mac ) 

### ISSUE THREAD

**Issue by MoniRaj1** [Accruent/robotframework-zoomba#141]
Hi , 

We have implemented Zoomba library to automate windows desktop application , is there a way we can extend this support to mac ?

**Comment by Wolfe1** [comment]
Hey @MoniRaj1, 

[From the looks of it here](http://appium.io/docs/en/drivers/mac/), its possible but would use the [appium-mac-driver](https://github.com/appium/appium-mac-driver) and [appium-for-mac](https://github.com/appium/appium-for-mac) to do so. For the most part the actions of the library should work, however I anticipate that keywords like 'Open Application' will have issues.

I don't currently have a Mac machine on hand to look into this unfortunately.

**Comment by MoniRaj1** [comment]
Thanks alot for your response @Wolfe1
