### ISSUE TITLE
dependency on psutil 5.7.3 failed installation - Microsoft Visual C++ 14.0 or greater is required.

### ISSUE THREAD

**Issue by arnabpandit** [Accruent/robotframework-zoomba#166]
could you pls update dependency to psutil 5.8.0? at least python 3.9 compatible wheels are available now.

**Comment by Wolfe1** [comment]
Should be merged and released soon, we have our updates automated but this one didn’t come in till this morning (guessing it released over the weekend).

**Comment by Wolfe1** [comment]
https://github.com/Accruent/robotframework-/releases/tag/2.7.3

Should hit pip in 10 minutes or so
