### ISSUE TITLE
Switch Application Desktop slow

### ISSUE THREAD

**Issue by robtail** [Accruent/robotframework-zoomba#170]
Hi,

First of all this Zoomba library is amazing. thank you very much for this. :)

My task to test a windows Desktop application, and i stucked with two issues. (i will open a separate issue)

My issue is with slow running when starting Switch Application Desktop. 

If our app started only with Open Application, 
Login page opens and I was able to type username and pw. then click on login button. (this is fast)
After login was success, application loading and main form appears.  (login disappears)
On this MAIN form i was not able to interact any of the elements! 
I was hopeless for one week and searching the  internet for help then i found an advise to open app=root. 
and then i found Zoomba. :)

So I started using the Switch To Desktop Test example 
Our app loaded after login and I was able to Click, Input, Send keys, etc. 
But each command issue takes 5-15 seconds (robot framework waits to issue this to WAD driver.)

So this is very very long, almost unusable because lots of interaction needed for each test case.

Can you pls advise how to solve the slowness issue? 

Calculator example is fast. 
CPU usage less than 20% (mostly winappdriver ) with my app.  Memory is 50%.  So these should not be the reason.

![image](https://user-images.githubusercontent.com/77631362/104943408-b8ea3a00-59db-11eb-99b8-0ac399d3839c.png)

test case 
![image](https://user-images.githubusercontent.com/77631362/104944291-00bd9100-59dd-11eb-898b-e6691cfdafc4.png)

Do you have any advise?  

Thanks in advance. 

Best Regards, 
Robert

**Comment by Wolfe1** [comment]
Hey @robtail,

Glad you are finding the library useful. We had the exact same issue you had. We had a login form that we could log in and it would create a new app window that we couldn't interact with. The reason things are going so slowly is due to the way WinAppDriver finds elements. Essentially its one big XML tree that it has to look through, we limit this by selecting an application to lower the scope. So right now when you are using the desktop session, the driver has to traverse ALL the applications on the desktop so this can run slower and slower depending on how many apps you have open (chrome, slack, etc).

The solution we have still uses the desktop session but only temporarily. You will want to still go through your usual login but after clicking login you will want to use [Switch Application By Name](https://accruent.github.io/robotframework-zoomba/DesktopLibraryDocumentation.html#Switch%20Application%20By%20Name) to attach to the new window.

It may take a bit to attach but once you are you will be able to do your actions in the new window. Do note that since your main window probably has more components that the automation may be slower but it should be much faster than working directly from the desktop session.

**Comment by robtail** [comment]
Hi Wolfe1, 

Thank you very much your instant and valuable response!
It was very interesting to me to understand the approach you describe. Thanks you very much !  :)

The only question is the sequence and the usage of Quit Application 
So i will 
1 Open Application 
2 Switch Application	Desktop
3. Launch Application
4 Login to app with App Login 
5. Quit Login
6 Switch Application By Name to Case Search - (which is the main window )
7 do test on case search.

I tried earlier the Switch Application By Name to Case Search but was not successful to switch to it.
Maybe i didnt use desktop before that, or use wrong name reference.

I try it now. 
Im not fully understand - Why do i need Desktop still if i Switch App By Name comes to the picture? but i will try without.

Many many thanks! :)

Best Regards, 
Robert

**Comment by robtail** [comment]
Update - Good News.

Hi Wolfe1,

Based on your advise i **got a great speed improvement**!!!

And the big outcome we **do not need use** Switch Application to Desktop! 

So i did this
1 in Suit setup i Start app (Open Application, then Quit Application)  # But no Desktop!!
2 in Test Setup - Launch Application   
4 in TC - Login to app with App Login
5. Sleep 7 
6. Switch Application By Name to Case Search 
7. do test steps on case search. (Sometimes they opens new windows)
8. Switch to and back from another other windows opened from step 7.
So works as should be.

Speed is improved, code is more clear to me. 
Many many thanks! :)

Can you advise how to eliminate "Sleep 7" in step 5?
i would avoid fix time delays... 

Best Regards,
Robert

**Comment by Wolfe1** [comment]
Great to hear @robtail a few notes from what you have said:

1. The sleep is unfortunately the best way I can see as the other solution may end up taking longer than 7 seconds on average anyway. In any case if you wanted something that was dynamic you would have to:
    1. Switch to the desktop session
    2. Wait for your new window to appear with something like [Wait Until Page Contains Element](https://accruent.github.io/robotframework-zoomba/DesktopLibraryDocumentation.html#Wait%20Until%20Page%20Contains%20Element) with a modified timeout parameter possibly. This is of course the part that may take more time than its worth though.
    3. Then attempt the switch application by name to the new window.
2. The suite setup model in the samples works great for newer windows apps like calculator as it allows the app to launch quickly between test cases. I have a feeling that your application may not be benefiting from it though especially with the login screen in the way. Once you have a few test cases set up I would suggest testing this to see what is faster:
    1. The setup you have now (open app and quit to 'prime the app and then launch the app per test case in the test setup)
    2. OR don't use the **suite** setup at all and just use 'open application' in the **test** setup.

So from your example it would be:
```
1 in Test Setup - Open Application
2 in TC - Login to app with App Login
3. Sleep 7
4. Switch Application By Name to Case Search
5. do test steps on case search. (Sometimes they opens new windows)
6. Switch to and back from another other windows opened from step 7.
```

**Comment by robtail** [comment]
Hi @Wolfe1 

Thanks again for the advise you gave, but i found a the dynamic way :) 

Im waiting for last element (login button) [disappear ](https://accruent.github.io/robotframework-zoomba/DesktopLibraryDocumentation.html#Wait%20Until%20Element%20Does%20Not%20Contain) from the screen (with a long timeout because my app is slow as hell :)

![image](https://user-images.githubusercontent.com/77631362/105054085-e386d200-5a71-11eb-85c1-221681ee1481.png)

Then execution continues when login screen disapear.

:)

Many thanks for support me!!

Best Regards, 
Robert

**Comment by Wolfe1** [comment]
Haha good to hear and thank you for using the tool!
