### ISSUE TITLE
Two (subsequent) clicking needed for buttons and checkbox.

### ISSUE THREAD

**Issue by robtail** [Accruent/robotframework-zoomba#171]
Hi,

Buttons and CheckBoxes needs to be clicking twice for working. (Manual tests needs to be pushed once)

1. First clicks seen in WAD commands and is visually seen on the application - seems to be pushed. but no action happens.
2. Second click also seen in WAD window and button seems to be pushed again, - and this time the action is doing.

The code in Robot Framework:
![image](https://user-images.githubusercontent.com/77631362/105050748-63ab3880-5a6e-11eb-9517-7fcf00930144.png)

WAD API commands for the above two code: 
`
==========================================
POST /session/5166D5D3-27CE-41B7-BC31-9722D6388F42/elements HTTP/1.1
Accept: application/json
Accept-Encoding: identity
Connection: keep-alive
Content-Length: 115
Content-Type: application/json;charset=UTF-8
Host: 127.0.0.1:4723
User-Agent: appium/python 1.0.2 (selenium/3.141.0 (python windows))

{"using": "xpath", "value": "//Button[@AutomationId='btnOK']", "sessionId": "5166D5D3-27CE-41B7-BC31-9722D6388F42"}
HTTP/1.1 200 OK
Content-Length: 98
Content-Type: application/json

{"sessionId":"5166D5D3-27CE-41B7-BC31-9722D6388F42","status":0,"value":[{"ELEMENT":"42.5505976"}]}

==========================================
POST /session/5166D5D3-27CE-41B7-BC31-9722D6388F42/element HTTP/1.1
Accept: application/json
Accept-Encoding: identity
Connection: keep-alive
Content-Length: 115
Content-Type: application/json;charset=UTF-8
Host: 127.0.0.1:4723
User-Agent: appium/python 1.0.2 (selenium/3.141.0 (python windows))

{"using": "xpath", "value": "//Button[@AutomationId='btnOK']", "sessionId": "5166D5D3-27CE-41B7-BC31-9722D6388F42"}
HTTP/1.1 200 OK
Content-Length: 96
Content-Type: application/json

{"sessionId":"5166D5D3-27CE-41B7-BC31-9722D6388F42","status":0,"value":{"ELEMENT":"42.5505976"}}

==========================================
POST /session/5166D5D3-27CE-41B7-BC31-9722D6388F42/element/42.5505976/click HTTP/1.1
Accept: application/json
Accept-Encoding: identity
Connection: keep-alive
Content-Length: 73
Content-Type: application/json;charset=UTF-8
Host: 127.0.0.1:4723
User-Agent: appium/python 1.0.2 (selenium/3.141.0 (python windows))

{"id": "42.5505976", "sessionId": "5166D5D3-27CE-41B7-BC31-9722D6388F42"}
HTTP/1.1 200 OK
Content-Length: 63
Content-Type: application/json

==========================================
POST /session/5166D5D3-27CE-41B7-BC31-9722D6388F42/element HTTP/1.1
Accept: application/json
Accept-Encoding: identity
Connection: keep-alive
Content-Length: 115
Content-Type: application/json;charset=UTF-8
Host: 127.0.0.1:4723
User-Agent: appium/python 1.0.2 (selenium/3.141.0 (python windows))

{"using": "xpath", "value": "//Button[@AutomationId='btnOK']", "sessionId": "5166D5D3-27CE-41B7-BC31-9722D6388F42"}
HTTP/1.1 200 OK
Content-Length: 96
Content-Type: application/json

{"sessionId":"5166D5D3-27CE-41B7-BC31-9722D6388F42","status":0,"value":{"ELEMENT":"42.5505976"}}

==========================================
POST /session/5166D5D3-27CE-41B7-BC31-9722D6388F42/element/42.5505976/click HTTP/1.1
Accept: application/json
Accept-Encoding: identity
Connection: keep-alive
Content-Length: 73
Content-Type: application/json;charset=UTF-8
Host: 127.0.0.1:4723
User-Agent: appium/python 1.0.2 (selenium/3.141.0 (python windows))

{"id": "42.5505976", "sessionId": "5166D5D3-27CE-41B7-BC31-9722D6388F42"}
HTTP/1.1 200 OK
Content-Length: 63
Content-Type: application/json

{"sessionId":"5166D5D3-27CE-41B7-BC31-9722D6388F42","status":0}`

Any advise why we have this ?

**Comment by Wolfe1** [comment]
Hmmm this is quite odd, It could be related to the fact that when you manually test this you first mouse over the element. 

Could you try using a 'mouse over' type keyword instead? Such as [Wait For And Mouse Over And Click Element](https://accruent.github.io/robotframework-zoomba/DesktopLibraryDocumentation.html#Wait%20For%20And%20Mouse%20Over%20And%20Click%20Element) to see if that clicks without the need for a second click?

**Comment by robtail** [comment]
Hi @Wolfe1 

Thanks for advise.

Unfortunately Wait For And Mouse Over And Click Element works very weird! depending on how to run the TC.

If i run the TC from RIDE it behaves like this 
Sometimes 
1 clicks on OK but nothing happens, or 
2 Not clicking on OK button but hover over date time picker of the windows machine!
3 Seem clicking on outside of the app!  - on the right bottom corner of the screen -  
this is the Windows Virtual Machine date time picker.
![image](https://user-images.githubusercontent.com/77631362/105056890-fbac2080-5a74-11eb-9ba8-57426d6a3e3f.png)

But from RIDE it never went over on Login screen!


If i run Robot Framework TC from CMD 
1 it always work properly if i have not maximize the Remote Desktop window.
2. mostly not work properly if i have Maximize the Remote Desktop window.

It seems to me it could be related to VM or RDP!

FYI. I have 3 screens.  Maybe it is relevant.

Unfortunately i cant test this app from my local machine. 
App is on client premises and i access it from Remote Desktop.

**Comment by Wolfe1** [comment]
We run some tests on virtual machines here as well however not in the way you are doing. If I am understanding correctly your setup is to have an app that is open in an RDP window but your test execution is being run on your local machine correct?

We open an RDP window that has our app running AND we run the test execution from that window as well. This is particularly helpful since while the test is running we are free to use our machines as we normally do (Just don't close or minimize the RDP window. Other windows can be opened in front of the RDP window but minimizing or closing seems to kill the test at least for us).

**Is it possible for you to do this? As in run your tests from the machine running the application?**

**Comment by robtail** [comment]
Hi @Wolfe1,

Sorry for misleading information. We have the same general scenario. 
We have access to VM, with RDP and run Robot Framework + Zoomba on the VM and we start the application on that machine. 
The reason i describe all my circumstances was because i was in the middle of investigation. 

But i made the final conclusion yesterday.
I realized our instability issues all related to full screen RDP access. 

If i use RDP window in a reduced size, most of the problems are resolved:
-Single click on buttons combo box-  works - no two click needed anymore. - so you can close this issue!
-this cures the instable outside clicks on the application area occasionally. 

Strange, because we in the team all have this problem on all 4 VM-s.  (3 remote session from India and one from me Hungary. )

Do you have any issue if you run RDP window in full screen?  

Best Regards, 
Robert

**Comment by Wolfe1** [comment]
@robtail We run our tests in full screen without issue, what RDP do you use? I believe most just use the one built into windows.

**Comment by robtail** [comment]
We use also standard RDP. It is somehow transfered from one to the another. i dont fully understand, how is it works: i RDP to one Domain\user and then its opens another login where i should login to my VM.  Sorry i cant provide clearer picture, because i dont fully understand....

**Comment by Wolfe1** [comment]
No problem, either way glad you are unblocked.
