### ISSUE TITLE
Checkbox Status/Value  - solution to add to wiki page

### ISSUE THREAD

**Issue by robtail** [Accruent/robotframework-zoomba#172]
Hi,

I figured out how to get Checkbox value/status, it takes a few hours, so i would like to share this with others :)

How to add it to Wikipage, or to [zoomba/DesktopLibraryDocumentation](https://accruent.github.io/robotframework-zoomba/DesktopLibraryDocumentation.html) ?

Attribute to evaluate should be Toggle.ToggleState (and not Value.Value as in your example)

${CBV}=	Zoomba.DesktopLibrary.Get Element Attribute	AutomationId_ofthechkbox	Toggle.ToggleState		
Zoomba.DesktopLibrary.Element Attribute Should Match	AutomationId_ofthechkbox 	Toggle.ToggleState	1		

Best Regards, 
Robert

**Comment by Wolfe1** [comment]
I can't seem to find this example you are talking about on the page, what keyword is it located in? Could you post a screenshot?

**Comment by robtail** [comment]
Hi Wolfe,

I figured out  how to get Checkbox value/status.
This is an example checkbox:
![image](https://user-images.githubusercontent.com/77631362/106456898-7110eb80-648e-11eb-9567-05a22fbbea5d.png)

Example checkbox's Automation Id is    **chkMatching**

This it the way to know is it checked or not, 
${CheckBoxValue}= Zoomba.DesktopLibrary.Get Element Attribute AutomationId_ofthechkbox Toggle.ToggleState
${CheckBoxValue} will be 1 if its checked.
${CheckBoxValue} will be 0 if its empty.

The example in Documentation column of [Get Element Attribute](https://accruent.github.io/robotframework-zoomba/DesktopLibraryDocumentation.html#Get%20Element%20Attribute) 
should show working example to get value 
Value.Value  - for general element
Toggle.ToggleState - for checkbox

this is the RIDE example of how to get a Checkbox value:
![image](https://user-images.githubusercontent.com/77631362/106457762-b97cd900-648f-11eb-926b-0b8f80579060.png)

i wanted to share this code with others, so thats why asked how to update wikipage...

Is it better explained now?

**Comment by Wolfe1** [comment]
Hey @robtail, 

Makes sense but a couple things:
- [Get Element Attribute](https://accruent.github.io/robotframework-zoomba/DesktopLibraryDocumentation.html#Get%20Element%20Attribute) is a keyword we extended from AppiumLibrary so the documentation that comes back is not set by us.
- I suspect that the example you have there is still going to be very specific to the product you are working on. So it probably wouldn't give a ton of value for others.

**Comment by robtail** [comment]
Hi Wolfe,

Apologies, i was not, clear. 

It is not a specific problem of my application it is general "problem" how to get Checkbox's value.

Any application's, (any) checkbox, Get Element Attribute  Value.Value **is null**.  
That was the initial issue for me.  (I assume You probably haven't tried yet :)  )

Then i searched how to get checkbox value, and found the solution.

So i suggested to update Zoomba [documentation](https://accruent.github.io/robotframework-zoomba/DesktopLibraryDocumentation.html) this part: 
![image](https://user-images.githubusercontent.com/77631362/106582156-f86c6680-6543-11eb-98c7-a8c178b3b66d.png)

with a better valuable examples as you did in [issue 168](https://github.com/Accruent/robotframework-zoomba/issues/168)
and i also suggests to give an example of how to get a Checkbox value:
${CheckBoxValue}= Zoomba.DesktopLibrary.Get Element Attribute chkMatching Toggle.ToggleState
Zoomba.DesktopLibrary.Element Attribute Should Match chkMatching Toggle.ToggleState 1

So do you think is it useful information?
