### ISSUE TITLE
"Switch Application By Name" is very slow if exact_match=false is used

### ISSUE THREAD

**Issue by frankstriegel** [Accruent/robotframework-zoomba#183]
Zoomba Version 2.8.0

If keyword "Switch Application By Name" is used in combination with exact_match=false it is much slower than using it with exact_match=true (by factor 2-4 if no other application is running but by factor 10-15 if some other applications are running).

You can test it by the follwing suite:

```
*** Settings ***
Library   Zoomba.DesktopLibrary

Suite Setup      Suite Initialization
Suite Teardown   Suite Finalization

*** Variables ***
${REMOTE_URL}   http://localhost:4723
${APP}          Microsoft.WindowsCalculator_8wekyb3d8bbwe!App

*** Test Cases ***
AppChange
    # ${calculator_handle}=  Open Application    ${REMOTE_URL}     platformName=Windows    deviceName=Windows   app=${APP}
    ${calculator_handle}=  Switch Application By Name  ${REMOTE_URL}  window_name=Rechner  exact_match=true  platformName=Windows    deviceName=Windows   app=${APP}
    Wait For And Click Element  accessibility_id=clearEntryButton
    Wait For And Click Element  accessibility_id=num1Button
    Wait Until Element Contains  accessibility_id=CalculatorResults      1

    # Switching to Word but don't know the name of the currently open word document (means I have to use exact_match=false)
    Switch Application By Name  ${REMOTE_URL}  window_name=Word  exact_match=false  platformName=Windows    deviceName=Windows
    Send Keys  Hello World 1  \ue007

    Switch Application  ${calculator_handle}
    Wait For And Click Element  accessibility_id=num2Button
    Wait Until Element Contains  accessibility_id=CalculatorResults      2

    # Switching to Word but using the exact document name
    Switch Application By Name  ${REMOTE_URL}  window_name=Dokument1 - Word  exact_match=true  platformName=Windows    deviceName=Windows
    Send Keys  Hello World 2  \ue007

    Switch Application By Name  ${REMOTE_URL}  window_name=Rech  exact_match=false
    Wait For And Click Element  accessibility_id=num3Button
    Wait Until Element Contains  accessibility_id=CalculatorResults      3

    # Switching to Word againg using exact_match=false to see whether there is some caching
    Switch Application By Name  ${REMOTE_URL}  window_name=Word  exact_match=false
    Send Keys  Hello World 3  \ue007

*** Keywords ***
Suite Initialization
    Driver Setup
    
Suite Finalization
    Driver Teardown
```

This results in the follwing log
![grafik](https://user-images.githubusercontent.com/79524456/108858759-ce5f0f00-75ec-11eb-83df-090ab5bc7fd6.png)

What can be done to improve the performance?

**Comment by simonmeggle** [comment]
I am facing similar issues (tested also with the newest version)...

**Comment by Wolfe1** [comment]
When we know the exact name of the window we are able to do a find like so:
```
window = desktop_session.find_element_by_name(window_name)`
```
Which is pretty quick but when we attempt a  search for an approximate name we have to use xpath:
```
window_xpath = '//Window[contains(@Name, "' + window_name + '")]'
window = desktop_session.find_element_by_xpath(window_xpath)
```
Xpath in WinAppDriver is slow and in this case effected by how many other programs your desktop has running. I attempted to test a few more xpath possibilities to see if what I was doing was ill-performant but I couldn't get a noticeable difference in execution speed.

This all ends up on the [WInAppDriver](https://github.com/microsoft/WinAppDriver) side which is closed source. [They promise that its not dead](https://github.com/microsoft/WinAppDriver/issues/1371) but we have yet to hear too much from them on it.

**Open to any suggestions you may have on how to improve this though!**

**Comment by Wolfe1** [comment]
@frankstriegel @simonmeggle 

See https://github.com/Accruent/robotframework-zoomba/pull/201 for a new keyword to try. This won't make the partial name search or xpath any faster but perhaps there is an id or class you could use that would be much faster.

[Switch Application By Locator](https://accruent.github.io/robotframework-zoomba/DesktopLibraryDocumentation.html#Switch%20Application%20By%20Locator)

**Comment by simonmeggle** [comment]
Thanks Brandon! 👍
