### ISSUE TITLE
Update robotframework-requests version

### ISSUE THREAD

**Issue by antrv** [Accruent/robotframework-zoomba#194]
Please update the version of robotframework-requests to the latest (0.8.2 at the moment)

**Comment by Wolfe1** [comment]
Hey, @antrv 

So 0.8.0 brought in a pretty breaking change that was going to require quite a bit of rework. These changes would then be temporary as in 0.9 we would be moving again to session less keywords. Once 0.9 hit a beta or stable version was when I planned to jump on this

Any particular reason you want/need this moved to latest robotframework-requests?

**Comment by antrv** [comment]
Hi @Wolfe1,

Thanks, that's ok. I'll rewrite my code with `robotframework-requests` 0.7.
I just use `robotframework-requests` 0.8 in the tests from the start. Now I switch to zoomba for testing WPF app (previously it was the buggy whitelibrary).

**Comment by Wolfe1** [comment]
@antrv If you are just using the DesktopLibrary portion of Zoomba I believe you could:

- clone the repo
- Set the requests version you want in requirements.txt
- build with 'pip install .'

Only the APILIbrary portion uses requests to my knowledge

**Comment by Wolfe1** [comment]
@antrv Looks like requests 0.9 just released so this may happen sooner than I anticipated. Probably in the next few weeks depending on level of effort to switch things over.

**Comment by Wolfe1** [comment]
Fixed in https://github.com/Accruent/robotframework-zoomba/releases/tag/2.9.0
