### ISSUE TITLE
Using Zoomba for webview2 component

### ISSUE THREAD

**Issue by Bhavnasewani** [Accruent/robotframework-zoomba#203]
Hi Team,

I have an application that is developed using Webview2 .net component. Basically, we have a desktop container for our Angular based app. This is run using the microsoft edge (chromium). 
I tried using Zoomba library for writing to a text field but the test case would fail giving an exception
No such elementException.

Any help on this would be appreciated

I have written very basic test case as shown below. The app opens but the element is not recognized. 

Open Application ${RemoteURL}  platform=Windows deviceName=Windows  app=${myapp}  window_name=${mywindowname}  exact_match=false

Input Text  xpath=//[@id="myTextBoxID"]    MysampleText

**Comment by Bhavnasewani** [comment]
For more information on webview2 feature and automation testing
Please check the link below:

https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/webdriver

**Comment by Wolfe1** [comment]
This will need some investigation but im not sure how soon I could look at this. In the meantime though

More than likely this would be controlled by attaching a selenium session (GUILibrary) to the app to control the web view. Something like this example but using GUILibrary instead of SeleniumLibrary: https://stackoverflow.com/questions/31661189/robot-framework-reuse-existing-browser-window-between-tests

Also if this is just a desktop container for your webapp you will probably have much more success and less heartache by simply testing the webapp directly using GUILibrary and a chrome/Edge browser.

**Comment by Bhavnasewani** [comment]
That's true if I test only the web app directly would solve my issue. But I am interested in testing the final product a user would get after developing an app using webview2 and which is an exe.

The link (for webview2) I shared has some sample exe and python code for running automation on it but I want it to be done using Robot Framework

Any directions would be of great help!

**Comment by Wolfe1** [comment]
Hey @Bhavnasewani  just letting you know I have the sample app loaded and will be doing some testing on this now, will let you know what I find.

**Comment by Wolfe1** [comment]
Ok @Bhavnasewani I think I have a solution for you to try.

Here is the branch I am using right now: https://github.com/Accruent/robotframework-zoomba/tree/WebView2

If you clone that locally and then run:
`pip install .`
From the main directory you can install it.

I have a demo script using the sample application provided by microsoft located in [~/samples/WebView-DesktopTest.robot](https://github.com/Accruent/robotframework-zoomba/blob/WebView2/samples/WebView-DesktopTest.robot). This script shows how to open the application, control the webview layer, and also control the application layer.

![rbmzmun3cR](https://user-images.githubusercontent.com/3010366/122806407-e4759700-d28f-11eb-8b72-779660606d9f.gif)

Let me know if that works for your app or any other thoughts / suggestions.
