### ISSUE TITLE
How to pass download directory path ?

### ISSUE THREAD

**Issue by deepaleekhare31** [Accruent/robotframework-zoomba#214]
How to pass download directory with options?

I tried the below code: But it did not work
${options}=   Get Edge Options
${options.use_chromium}=    Set Variable   True
${options.add_experimental_option["download.default_directory"]}    Set Variable   C:\\Downloads
Open Browser   http://www.google.com    browser=Edge     options=${options}

Could you please help ?

**Comment by deepaleekhare31** [comment]
@Wolfe1 Could you please help?

**Comment by Wolfe1** [comment]
@deepaleekhare31 Not really sure but a quick google search found me this: https://stackoverflow.com/questions/62817645/need-to-set-the-download-directory-chromium-edge-browser-using-selenium

From the sample code it seems they are using AddUserProfilePreference for Edge. The sample is in C# but that should give you an idea on things to try.

**Comment by deepaleekhare31** [comment]
Hello,
with python this works:
options.add_experimental_option("prefs", {"download.default_directory": "C:\\Downloads"})

But how to use the same in robot scripts?

**Comment by deepaleekhare31** [comment]
Heyyy i got a solution:

    ${options}=   Get Edge Options
    ${prefs} =    Create Dictionary    download.default_directory=C:\\Downloads
    **Call Method    ${options}    add_experimental_option    prefs    ${prefs}**
    Call Method    ${options}    add_argument    --headless
    Open Browser   http://example.com    browser=Edge     options=${options}

**Comment by Wolfe1** [comment]
Excellent! Closing this issue out then.
