### ISSUE TITLE
Zoomba.APILibrary - is there a way to ignore warnings as in requests library?

### ISSUE THREAD

**Issue by UliSei** [Accruent/robotframework-zoomba#234]
Running my RF scripts  with docker on internal servers I get lots of warnings:
`/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'proxy'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings`

In requests library, keyword **Create Session** there is a possibility to use the `disable_warnings` argument, see [here](https://marketsquare.github.io/robotframework-requests/doc/RequestsLibrary.html#Create%20Session).

There is no **Create Session** keyword in Zoomba.APILibrary. 
And the **Call Post Request** has no `disable_warnings` argument.
So is there another way to suppress warnings?

**Comment by Wolfe1** [comment]
I think what you are looking for is [Supress Insecure Request Warnings](https://accruent.github.io/robotframework-zoomba/APILibraryDocumentation.html#Suppress%20Insecure%20Request%20Warnings).

**Comment by UliSei** [comment]
Fantastic! 
That's exactly what I was looking for.
Implemented it before the  **Call Post Request**  and it works fine.
Thank you!
