### ISSUE TITLE
Open_Application does not always start app with webdriver

### ISSUE THREAD

**Issue by mengelskirchen** [Accruent/robotframework-zoomba#244]
# Issue
DesktopLibrary#open_application does not start the app with webdriver#remote when the attribute window_name is given.

The result is that the application may be started with an other user than webdriver is running with and as it with other user rights than intended.

https://github.com/Accruent/robotframework-zoomba/blob/69012ddaff5803cbf3d054b07dd6b57ed2f7923f/src/Zoomba/DesktopLibrary.py#L280-L299

**Comment by Wolfe1** [comment]
While I agree that what you have here is cleaner I believe there was a reason I went with subprocess before. I think it had to do with Webdriver.Remote failing after the splash screen disappears.

I will take a look on my end though with some internal tests with splash screens sometime this week.
 
Thanks!
