### ISSUE TITLE
Remote_URL not working from Desktop Library Documentation

### ISSUE THREAD

**Issue by Mavnus04** [Accruent/robotframework-zoomba#249]
While trying to get the Desktop Library up and running, I ran into an issue with example `remote_url` in https://accruent.github.io/robotframework-zoomba/DesktopLibraryDocumentation.html 
Most `remote_url` example is given as `http://localhost:4723/wd/hub`, but that didn't work for me.  I had to use 'http://localhost:4723`. 

TestZoomba.robot that worked for me:

    *** Settings ***
    Library     Zoomba.DesktopLibrary  run_on_failure=No Operation

    *** Test Cases ***
    Test Zoomba Desktop Library
        [Tags]  Zoomba
        [Setup]  Driver Setup
        Log to console  ...
        Switch Application By Name  http://localhost:4723  Untitled - Notepad
        [Teardown]  Driver Teardown

RunTestZoomba.bat:

    CD /D "%~dp0"

    robot -d Output/Zoomba -T ^
    --include Zoomba ^
    -s Suites.TestZoomba .

Does the documentation need to be updated? 
Is my setup wrong? 

    C:\>pip show robotframework-zoomba
    Name: robotframework-zoomba
    Version: 2.13.1
    Summary: Robot Framework mini-framework.
    Home-page: https://github.com/Accruent/zoomba
    Author:
    Author-email:
    License: GPL-3.0
    Location: c:\program files\python37\lib\site-packages
    Requires: msedge-selenium-tools, psutil, python-dateutil, requests, robotframework, robotframework-appiumlibrary, robotframework-requests, robotframework-seleniumlibrary, robotframework-sudslibrary-aljcalandra, selenium
    Required-by:

    C:\>python
    Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32

WinAppDriver installed at: `C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe`

Windows 10

**Comment by Wolfe1** [comment]
- Originally this was set up to use Winappdriver through Appium which would indeed use the remote_url of 
  - Example here: https://github.com/Accruent/robotframework-zoomba/blob/master/samples/Appium-DesktopTests.robot
- Later on, we added the ability to run with the WinAppDriver stand alone
   -  Example here: https://github.com/Accruent/robotframework-zoomba/blob/master/samples/WinAppDriver-DesktopTests.robot

So yes your setup is just fine and the docs are "ok" in their current state but could use an update to show both ways it could be used.

**Comment by Mavnus04** [comment]
Ahh, alright.  Thank you for the clarification.

**Comment by Wolfe1** [comment]
Fixed by #273
