### ISSUE TITLE
[🚀 Feature]: WPF-based app Scrollable content

### ISSUE THREAD

**Issue by jsperafico** [Accruent/robotframework-zoomba#270]
### Feature and motivation

Hey everyone,
First of all congratulations for your work so far! It's quite an accomplishment!

As per your documentation, the it should be possible to scroll through a content on the screen.
Unfortunately while attempting to do that, I noticed in order to perform such action the "touch" functionality is being used.
To my frustration, I discovered that our WPF app doesn't support such action.

Would be possible to identify the presence of scroll bar on a given context and then the amount we would like to scroll?

```
Scrollable Content
     [Documentation]    Given a window, panel or any scrollable content it should be able to scroll horizontally or vertically
     ...                             an amount based on current visualization.
     [Arguments]     ${locator}    ${horizontal}=${0}   ${vertical}=${0}
     ....
Scrollable Content To
     [Documentation]    Given a window, panel or any scrollable content it should be able set the horizontal or vertical scroll
     ...                             to a given percentage.
     [Arguments]     ${locator}    ${horizontal}=${0}   ${vertical}=${0}
```

Thanks anyway.

### Usage example

Something like:

```
Scrollable Content        xpath=//Window[@Name="Sample"]     horizontal=30px   vertical=60px
Scrollable Content To    xpath=//Window[@Name="Sample"]     horizontal=30%   vertical=60%
```

**Comment by Wolfe1** [comment]
I will have to take a look at this when I get time. I believe the reason we went with the touch scroll was due to that being the [API that was supported by WinAppDriver](https://github.com/microsoft/WinAppDriver/blob/master/Docs/SupportedAPIs.md). 

Has been awhile though so perhaps there is something that can be done here.

**Comment by Wolfe1** [comment]
Code moved to https://github.com/Accruent/robotframework-applicationlibrary so losing this issue.
